# Generated by Django 2.0.9 on 2019-03-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerytask',
            name='args',
            field=models.TextField(blank=True, null=True),
        ),
    ]
